export const GATEWAY_CONF = {
	ODATA_SERVICE: "/ZSAP_TOOLS_CORE_SRV",
	ODATA_TRANSP_SERVICE: "/ZSAP_TOOLS_TRANS_ORDER_SRV",
	ODATA_PATH: "/sap/opu/odata/sap",
};
export const SAP_TOOLS_OBJECT_NAMES = {
	SAP_TOOLS_GW_CUSTOM_CLASS: "ZCL_ZSAP_TOOLS_CORE_DPC_EXT",
};
